### ISSUE TITLE
ImportError: cannot import name 'get_cmap' from 'matplotlib.cm'

### ISSUE THREAD

**Issue by ej159** [SarthakJariwala/seaborn-image#875]
ImportError: cannot import name 'get_cmap' from 'matplotlib.cm'

Trying to import the library does not work with matplotlib 3.11.1. This is to do with [matplotlib changing their API](https://stackoverflow.com/questions/78628960/module-matplotlib-cm-has-no-attribute-get-cmap)

**Comment by SarthakJariwala** [comment]
Thanks for reporting - this is now fixed in v0.10.1
